#!/usr/bin/env python3
"""Assemble the hostable site (and the Artifact build) from index.html.

  site/                 landing page + shared images
  site/play/            the app as a PWA (manifest, service worker, icons)
  artifact.html         the Artifact build (style + body only)

The service worker is versioned by a hash of the app, so every republish
invalidates the old cache automatically and a girl never gets a stale playbook.
"""
import re, json, hashlib, pathlib, shutil

ROOT = pathlib.Path(__file__).parent
app  = (ROOT/'index.html').read_text()
ver  = hashlib.sha256(app.encode()).hexdigest()[:12]
site, play = ROOT/'docs', ROOT/'docs'/'play'   # GitHub Pages serves /docs
play.mkdir(parents=True, exist_ok=True)

# ---- the app itself -------------------------------------------------------
(play/'index.html').write_text(app)

# ---- manifest -------------------------------------------------------------
(play/'manifest.webmanifest').write_text(json.dumps({
  "name": "St. Cecilia Freshman Powderpuff Playbook",
  "short_name": "Powderpuff",
  "description": "Every play we run, animated. Pick your position and watch where you go.",
  "start_url": "./",
  "scope": "./",
  "display": "standalone",
  "orientation": "portrait",
  "background_color": "#faf9f8",
  "theme_color": "#CE1141",
  "icons": [
    {"src": "icon-192.png", "sizes": "192x192", "type": "image/png"},
    {"src": "icon-512.png", "sizes": "512x512", "type": "image/png"},
    {"src": "icon-maskable-512.png", "sizes": "512x512", "type": "image/png", "purpose": "maskable"}
  ]
}, indent=2))

# ---- service worker -------------------------------------------------------
(play/'sw.js').write_text("""/* generated by build.py - do not edit */
const V = 'pp-%s';
const SHELL = ['./','./index.html','./manifest.webmanifest',
  './icon-192.png','./icon-512.png','./icon-maskable-512.png',
  './apple-touch-icon.png','./favicon-32.png'];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(V).then(c => c.addAll(SHELL)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(ks => Promise.all(ks.filter(k => k !== V).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener('fetch', e => {
  const r = e.request;
  if (r.method !== 'GET') return;
  /* The page itself: network first, so a republished playbook shows up as soon
     as she has signal - but fall back to cache so it still opens on the field. */
  if (r.mode === 'navigate') {
    e.respondWith(fetch(r).then(res => {
      const copy = res.clone(); caches.open(V).then(c => c.put('./', copy)); return res;
    }).catch(() => caches.match('./').then(m => m || caches.match('./index.html'))));
    return;
  }
  e.respondWith(caches.match(r).then(m => m || fetch(r)));
});
""" % ver)

# ---- artifact build -------------------------------------------------------
# Anchored to column 0 so a stray "<style>" inside a comment or a string can
# never hijack the capture - which is exactly what happened once.
style = re.search(r'(?m)^<style>$\n(.*?)^</style>$', app, re.S).group(1)
body  = re.search(r'(?m)^<body>$\n(.*?)^</body>$',  app, re.S).group(1)
art = '<title>Freshman Powderpuff Playbook</title>\n<style>'+style+'</style>\n'+body.strip()+'\n'
(ROOT/'artifact.html').write_text(art)

# ---- checks ---------------------------------------------------------------
js = re.findall(r'<script>(.*?)</script>', art, re.S)[-1]
assert js.count('{') == js.count('}'), 'unbalanced braces in artifact script'
assert 'serviceWorker' not in art, 'SW registration leaked into the artifact'
for f in ('icon-192.png','icon-512.png','icon-maskable-512.png','apple-touch-icon.png','favicon-32.png'):
    assert (play/f).exists(), 'missing icon '+f
print('version   ', ver)
print('app       ', len(app), 'bytes ->', play/'index.html')
print('artifact  ', len(art), 'bytes')
print('site tree ', sorted(p.relative_to(ROOT).as_posix() for p in site.rglob('*') if p.is_file()))
